server:
  url: ${server.domain}:${server.port}
spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}


  # Flyway
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  mail:
    host: smtp.mail.ru
    port: 587
    username: xandaqulov@mail.ru
    password: 6uTQvoY6HldZxhFLVYoW
    protocol: smtps

    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000


  # Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
