CREATE TABLE regions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50) NOT NULL UNIQUE,
    name_uz       VARCHAR(100) NOT NULL,
    name_ru       VARCHAR(100) NOT NULL,
    name_en       VARCHAR(100) NOT NULL,
    type          VARCHAR(20) NOT NULL,
    sort_order    INTEGER NOT NULL DEFAULT 0,
    created_date  TIMESTAMP,
    modified_date TIMESTAMP,
    created_by    BIGINT,
    modified_by   BIGINT,
    deleted       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_regions_type CHECK (type IN ('REGION', 'REPUBLIC', 'CITY')),
    CONSTRAINT chk_regions_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_regions_deleted_sort_order
    ON regions (deleted, sort_order);
