server:
  url: ${server.domain}:${server.port}

spring:
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
  application:
    name: category-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
