server:
  url: ${SERVER_URL:${server.domain}:${server.port}}

spring:
  application:
    name: location-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8761/eureka/}
